# Generated by Django 3.2.7 on 2024-04-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='balance',
            field=models.CharField(default=5000, max_length=150),
            preserve_default=False,
        ),
    ]
